Fix roundtrip errors
projectcypress/cdatools pull request #127
Opened 2017-06-05 13:22 UTC by dczulada

Providers need to export address and specialty
SOP is Source of Payment Typology
make hqmfQRDAMapElem map for R3.1
Add SNOMED-CT as prefred diagnosis code
Add negationOid to DcKey to account for the same oid being used for negations and non-negations

2017-06-05 13:35 UTC, tstrass requested changes

2017-06-05 13:35 UTC, tstrass commented on models/hds.go
> +  for _, oidsElem := range hqmfQrdaOids_r3_1 {
Can remove the TODO and indent this loop to be in alignement

2017-06-05 13:35 UTC, tstrass commented on models/hqmf_document.go
> +	NegationOid		string
alignment is off

2017-06-05 13:35 UTC, tstrass commented on models/hqmf_document.go
> +		if dataCriteria.Negation == true {
`== true` redundant, can be removed

2017-06-05 16:20 UTC, tstrass approved these changes

2017-06-08 15:18 UTC, ljades approved these changes

2017-06-08 15:18 UTC, merged