CCN NPI fixes
projectcypress/cdatools pull request #147
Opened 2017-07-13 18:23 UTC by okeefm

Built a better system for adding CCNs/NPIs to Cat I headers. Basically, the system looks for the given `root` ID in the Provider Performances for a patient. If that's not found, it puts in the default.

2017-07-13 18:49 UTC, tstrass requested changes

2017-07-13 18:49 UTC, tstrass commented on exporter/templates/cat1/r3/cat1.xml
> +          <id root="2.16.840.1.113883.4.6" extension="{{.}}" />
Just going off of [this template in HDS](https://github.com/projectcypress/health-data-standards/blob/master/templates/cat1/r3/show.cat1.erb#L87), these provider ID's should only be there if `CMSCompatibility` is on (and same for R3.1, R4)

2017-07-13 18:49 UTC, tstrass commented on models/provider.go
> +		if str != "" {
Minor nitpicks but can you make the assignment to str an initialization statement for the if? And maybe rename `str` to `rootID` or `id`, and `prov` to `provs`?

2017-07-14 14:06 UTC, okeefm commented on exporter/templates/cat1/r3/cat1.xml
> +          <id root="2.16.840.1.113883.4.6" extension="{{.}}" />
The provider IDs are allowed by the HL7 Implementation Guide, they are just only required by the CMS IG. Cypress generates NPIs for all providers, but if there isn't an NPI, this function will insert "1234567893" instead, which is a valid NPI.

2017-07-14 14:24 UTC, tstrass requested changes
Needs rebase+make and the issue Dave pointed out with calling `Record.ProviderIdentifiersForRoot` needs to be addressed

2017-07-14 19:38 UTC, dczulada approved these changes
Appears to work

2017-07-14 19:49 UTC, tstrass approved these changes

2017-07-14 19:49 UTC, merged