Export results using the result template. Allow for import of results…
projectcypress/cdatools pull request #159
Opened 2017-08-02 20:12 UTC by dczulada

… in a value element or Result template.

2017-08-03 18:34 UTC, mattrbianchi approved these changes

2017-08-03 19:30 UTC, okeefm requested changes

2017-08-03 19:30 UTC, okeefm commented on importer/lab_result.go
> +	var valuePath = xpath.Compile(".//cda:value")
Something like `"./cda:value | ./cda:entryRelationship[@typeCode='REFR']/cda:observation/cda:value"`

2017-08-07 18:38 UTC, okeefm approved these changes

2017-08-07 19:44 UTC, tstrass approved these changes

2017-08-07 19:45 UTC, merged