Export integration fixes
projectcypress/cdatools pull request #87
Opened 2017-03-13 18:43 UTC by tstrass

This contains fixes to bugs identified by integrating `cdatools` export with `cypress`, and running the Cypress API Measure Evaluator. At this point, the integration is not finished, but this PR contains the first wave of bug fixes.

2017-03-13 18:44 UTC, okeefm requested changes

2017-03-13 18:44 UTC, okeefm commented on exporter/templates/cat1/r3_1/_record_target.xml
> +        <raceCode code="{{escape .Race.Code}}" {{if .Race.DisplaName }}displayName="{{escape .Race.DisplayName}}"{{end}} codeSystemName="CDC Race and Ethnicity" codeSystem="2.16.840.1.113883.6.238"/>
Should be `.Race.DisplayName` in the `if`

2017-03-13 18:50 UTC, tstrass commented on exporter/templates/cat1/r3_1/_record_target.xml
> +        <raceCode code="{{escape .Race.Code}}" {{if .Race.DisplaName }}displayName="{{escape .Race.DisplayName}}"{{end}} codeSystemName="CDC Race and Ethnicity" codeSystem="2.16.840.1.113883.6.238"/>
thanks, fixed

2017-03-13 19:13 UTC, okeefm requested changes
Need to recompile `templates.go` now that you've made this change

2017-03-14 15:40 UTC, sylinmino commented on exporter/templates/cat1/r3/_record_target.xml
> +      <birthTime value="{{timeToFormat .BirthDate "20060102"}}"/>
I see all the other ones were changed to valueOrNullFlavor. Why not this one?

2017-03-14 15:40 UTC, sylinmino commented on exporter/templates/cat1/r3_1/_record_target.xml
> +      <birthTime value="{{timeToFormat .BirthDate "20060102"}}"/>
Same curiosity as with r3.

2017-03-14 16:17 UTC, tstrass commented on exporter/templates/cat1/r3/_record_target.xml
> +      <birthTime value="{{timeToFormat .BirthDate "20060102"}}"/>
Because not all time values can have an unknown state. The IG does not specify the `nullFlavor` possibility for this particular value.

2017-03-14 16:17 UTC, tstrass commented on exporter/templates/cat1/r3_1/_record_target.xml
> +      <birthTime value="{{timeToFormat .BirthDate "20060102"}}"/>
Same answer as with the other @sylinmino

2017-03-14 16:21 UTC, sylinmino commented on exporter/templates/cat1/r3/_record_target.xml
> +      <birthTime value="{{timeToFormat .BirthDate "20060102"}}"/>
Ah, gotcha.

2017-03-14 16:23 UTC, ljades approved these changes

2017-03-14 20:12 UTC, okeefm approved these changes

2017-03-14 20:12 UTC, merged